### ISSUE TITLE
Gif working without click event

### ISSUE THREAD

**Issue by vikramjit575** [benwiley4000/react-gif-player#12]
I am using the same code and when my page loads gif starts playing by itself without click event

**Comment by benwiley4000** [comment]
Thanks for pointing out your issue! I'm wondering a few things that will help me diagnose this:

1. Are you specifying a `still` prop? (It's fine not to, but the calculated still frame won't be available until the gif has fully loaded).
2. Is the component in the playing state (i.e. the button is hidden)?
3. Does it stop playing after the gif has loaded?

Thanks again

**Comment by vikramjit575** [comment]
Hi

1.Yes i am specifying a still prop and its value is still image of the gif

Here is how i used it
`<GifPlayer gif="public/images/GuruRamDass.gif" still="public/images/GuruRamDass.jpg" /> `

3.No it keeps on playing by its own

**Comment by vikramjit575** [comment]
I tested it after removing still props.It works fine after that:)

**Comment by benwiley4000** [comment]
Glad you found something that's working for you! 🙂 However I'm still a bit confused about the issue you're experiencing when you do specify the still frame. I'd love to help solve it - is there any way you could provide a repo demoing the problem?

**Comment by benwiley4000** [comment]
I should add, not specifying a `still` probably does look fine while you're testing locally, but it may look less good on a slow internet connection.

**Comment by vikramjit575** [comment]
yes thanks a lot for addressing my concern and i will update my repo very soon:)

**Comment by benwiley4000** [comment]
Thanks I look forward to it! Please keep me posted.

**Comment by benwiley4000** [comment]
@vikramjit575 I'd still love to see your code example when available. Will you still have one soon?

**Comment by andrewjroyce** [comment]
When I have both gif and still set to the same .gif I want to use, it autoplays - which is the behavior I want anyway.

**Comment by benwiley4000** [comment]
@andrewjroyce hm, that would be expected behavior. There's no validation on the image source you provide for either prop, so providing your gif as the `still` would mean the gif would play.

However that seems undesirable - you won't have a "paused" state to go back to.

Do you think there should be a `defaultPaused` prop (`true` by default)?

**Comment by andrewjroyce** [comment]
I've combined this with a tooltip, so it automatically plays on hover (tooltip opens) and stops on leave (tooltip closes) 
I don't see a need for that as a prop as the default is already paused, and that behavior can be circumvented with the method I described.

**Comment by benwiley4000** [comment]
@andrewjroyce just to humor me, could you provide a code snippet demonstrating what you've just described? I'm curious, and also not sure I'm totally following.

**Comment by benwiley4000** [comment]
Closing as there's been no followup and the `autoplay` prop is introduced in [v0.3.0](https://github.com/benwiley4000/react-gif-player/releases/tag/v0.3.0). Please comment if you believe something here hasn't been addressed! :slightly_smiling_face:
