### ISSUE TITLE
React 16 propTypes

### ISSUE THREAD

**Issue by nicubarbaros** [benwiley4000/react-gif-player#14]
Hey do you intend to update this package to use propTypes not from react but from the `prop-types` package?

**Comment by nicubarbaros** [comment]
PR #15 . Please check.

**Comment by benwiley4000** [comment]
I'll look at the PR soon thanks - we've already made this update in the "next" branch but it makes sense that the current version should be updated.

**Comment by benwiley4000** [comment]
Hey, I'm really sorry - I thought this was on a similarly named repository where we were already using prop-types. Got confused! I've merged your PR.
