### ISSUE TITLE
Published version to npm

### ISSUE THREAD

**Issue by AquiGorka** [benwiley4000/react-gif-player#16]
Could the `npm` version hold different code to this repo?

I am getting the `Prop.types` error from before (#15) in a fresh install.

**Comment by benwiley4000** [comment]
It could, and it does! Looks like I forgot to publish a new version. I'll do that shortly.

**Comment by benwiley4000** [comment]
@AquiGorka I just pushed [v0.2.3](https://github.com/benwiley4000/react-gif-player/releases/tag/v0.2.3) to npm. Let me know if there are any issues! :)
