### ISSUE TITLE
Gif is not autoplaying

### ISSUE THREAD

**Issue by Kevin-Do** [benwiley4000/react-gif-player#20]
```jsx
import GifPlayer from "react-gif-player";

<GifPlayer gif="https://i.imgur.com/WjhGJKb.gif" autoplay={true} />
```
I have to click in order to play the gif.
This gif is not autoplaying with the autoplay set to true? 
Am I using this correctly?

**Comment by benwiley4000** [comment]
Thanks @Kevin-Do for flagging this - I've released v0.3.1 to fix. Looks like I missed a spot!

cc @AquiGorka
