### ISSUE TITLE
GifPlayer doesn't allow to give className to img tag.

### ISSUE THREAD

**Issue by Ashviniv** [benwiley4000/react-gif-player#22]
I am trying to assign a _className_ to the _img_ tag used in GifPlayer using className attribute on img tag. But, it is not getting applied.
Following code I used:

`<GifPlayer gif={awsGIF} autoplay={true} className="img-fluid aws-gif" />`

Please correct me, if I am doing anything wrong.

**Comment by benwiley4000** [comment]
@Ashviniv you're doing nothing wrong! Thanks for flagging this. :slightly_smiling_face:  Looks like I accidentally removed the line that passes props through to the `img` tag when I released v0.3.0. I'll add it back... momentarily...

**Comment by benwiley4000** [comment]
@Ashviniv I've released [v0.4.1](https://github.com/benwiley4000/react-gif-player/releases/tag/v0.4.1). Let me know if that works for you.

**Comment by benwiley4000** [comment]
Closing this for now since there's been no response, and I'm fairly certain the issue is solved. Let me know if you have any concerns! :slightly_smiling_face:
