### ISSUE TITLE
Upgrade to latest webpack/webpack-dev-server

### ISSUE THREAD

**Issue by benwiley4000** [benwiley4000/react-gif-player#23]
webpack and webpack-dev-server need to be upgraded to their latest stable released versions. This will mean upgrading some related dependencies and updating the webpack config.

After this change:
* `npm run build` should still run without errors
* `npm run dev` should still create the dev server without errors
* `npm audit` should report no security vulnerabilities

**Comment by ronaiza-cardoso** [comment]
I'm on this

**Comment by benwiley4000** [comment]
Great! :)

**Comment by benwiley4000** [comment]
Opening this up for others to contribute. The submitted PR did not address the posted issue.

**Comment by benwiley4000** [comment]
Done in https://github.com/benwiley4000/react-gif-player/commit/0aa9464e35404014b668efb362a3991e80e46ad2, released in [v0.4.2](https://github.com/benwiley4000/react-gif-player/releases/tag/v0.4.2)
